import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { getUserIdFromExtensionAuth } from '@/lib/extension/auth'
import { generateNetworkMessage } from '@/lib/ai/network-message'

const AUTO_DRAFT_LOOKBACK_HOURS = 12
const AUTO_DRAFT_PREVIEW_LIMIT = 180

function normalizeProfileUrl(raw: string) {
  try {
    const url = new URL(raw)
    const pathname = url.pathname.replace(/\/$/, '')
    return `${url.origin}${pathname}`
  } catch {
    return ''
  }
}

export async function POST(request: Request) {
  try {
    const apiKey =
      process.env.GEMINI_API_KEY ?? process.env.GOOGLE_GENERATIVE_AI_API_KEY

    const userId = await getUserIdFromExtensionAuth(request)
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const body = (await request.json()) as {
      acceptances?: Array<{ name?: string; company?: string; profileUrl?: string }>
    }

    const acceptances = Array.isArray(body.acceptances) ? body.acceptances : []
    if (acceptances.length === 0) {
      return NextResponse.json({ updated: 0, matched: 0 })
    }

    let matched = 0
    let updated = 0
    let autoGenerated = 0
    let autoDraftSkipped = 0
    const matchedConnections: Array<{
      id: string
      name: string
      profileUrl: string | null
    }> = []
    const autoGeneratedDrafts: Array<{
      connectionId: string
      draftId: string
      preview: string
    }> = []

    const processedConnectionIds = new Set<string>()
    const profile = await prisma.userProfile.findUnique({
      where: { userId },
      select: {
        yearsOfExp: true,
        techStack: true,
        targetRoles: true,
        introSummary: true,
      },
    })
    const lookbackTime = new Date(Date.now() - AUTO_DRAFT_LOOKBACK_HOURS * 60 * 60 * 1000)

    for (const acceptance of acceptances) {
      const rawUrl = acceptance.profileUrl?.trim() || ''
      const normalizedUrl = normalizeProfileUrl(rawUrl)

      let connection = null

      if (normalizedUrl) {
        const altUrl = normalizedUrl.endsWith('/')
          ? normalizedUrl.slice(0, -1)
          : `${normalizedUrl}/`

        connection = await prisma.connection.findFirst({
          where: {
            userId,
            OR: [
              { profileUrl: { equals: normalizedUrl, mode: 'insensitive' } },
              { profileUrl: { equals: altUrl, mode: 'insensitive' } },
            ],
          },
        })
      }

      if (!connection) {
        const name = acceptance.name?.trim()
        const company = acceptance.company?.trim()
        if (name && company) {
          connection = await prisma.connection.findFirst({
            where: {
              userId,
              name: { equals: name, mode: 'insensitive' },
              company: { equals: company, mode: 'insensitive' },
            },
          })
        }
      }

      if (connection) {
        if (processedConnectionIds.has(connection.id)) {
          continue
        }
        processedConnectionIds.add(connection.id)

        matched += 1
        matchedConnections.push({
          id: connection.id,
          name: connection.name,
          profileUrl: connection.profileUrl,
        })

        const wasConnected = connection.status === 'CONNECTED'
        if (!wasConnected) {
          await prisma.connection.update({
            where: { id: connection.id },
            data: {
              status: 'CONNECTED',
              dateAccepted: connection.dateAccepted || new Date(),
            },
          })
          updated += 1

          if (apiKey) {
            const recentDraft = await prisma.generatedMessage.findFirst({
              where: {
                connectionId: connection.id,
                generatedAt: { gte: lookbackTime },
              },
              select: { id: true },
              orderBy: { generatedAt: 'desc' },
            })

            if (recentDraft) {
              autoDraftSkipped += 1
            } else {
              try {
                const generated = await generateNetworkMessage({
                  apiKey,
                  profile,
                  connection: {
                    id: connection.id,
                    name: connection.name,
                    company: connection.company,
                    role: connection.role,
                    jobTitle: connection.jobTitle,
                    jobUrl: connection.jobUrl,
                    notes: connection.notes,
                  },
                  variation: 'balanced',
                })

                if (generated.ok) {
                  const created = await prisma.generatedMessage.create({
                    data: {
                      connectionId: connection.id,
                      message: generated.text,
                    },
                    select: {
                      id: true,
                      message: true,
                    },
                  })
                  autoGenerated += 1
                  autoGeneratedDrafts.push({
                    connectionId: connection.id,
                    draftId: created.id,
                    preview: created.message.slice(0, AUTO_DRAFT_PREVIEW_LIMIT),
                  })
                }
              } catch (error) {
                console.error(`AI draft generation failed for connection ${connection.id}:`, error)
              }
            }
          }
        }
      }
    }

    return NextResponse.json({
      updated,
      matched,
      matchedConnections,
      autoGenerated,
      autoDraftSkipped,
      autoGeneratedDrafts,
    })
  } catch (error: unknown) {
    console.error('Error processing acceptances:', error)
    return NextResponse.json({ error: 'Failed to process acceptances' }, { status: 500 })
  }
}
